### ISSUE TITLE
Map Search on Listing page

### ISSUE THREAD

**Issue by jardavies89** [mshareef123/CCFarmApp#20]
I'm not making much progress on this one - for some reason when I include the ['uiGmapgoogle-maps'] to the listing controller, like the map view does, it makes the entire foodbank site not load. The debugger log gives me nothing and I'm at a loss as to how to fix it.  I'll check in what I have when I make my commit, but I'm completely stumped on this issue.

**Comment by eaziz** [comment]
Hi Jared

**Comment by eaziz** [comment]
Hi Jared,

I think I know what is causing the issue, it has to do with module naming, listing controller should be added to foodbankfarm.map module as it has been done in MapController only then you will be able to inject uiGmapgoogle-maps into it and use gmap geometry library

**Comment by jardavies89** [comment]
We've made progress on this - I got the search bar and the calculations for the distance working on the map page, but the listing page is having issues with including the Places API.  Azis is going to help with that, and once we figure it out it'll pretty much be plug and play - the sort mechanism to swap between the two methods (by distance or name) is a smaller effort.

**Comment by jardavies89** [comment]
Okay distance sort is working - small bug with it but I'll ask about it later cause I'm sure we can fix it easily.
