### ISSUE TITLE
Reset filter is not reloading map/listing

### ISSUE THREAD

**Issue by eaziz** [mshareef123/CCFarmApp#43]
When you hit Reset filter it should reload listing and map.

**Comment by jardavies89** [comment]
So I noticed that when I tried to force this to happen with $scope.$apply that I got a console warning with '$apply is already in progress.'  I think something weird is going on here, will dig deeper.

**Comment by jardavies89** [comment]
Annnd fixed it, not sure where the apply error came into play though...
