### ISSUE TITLE
selected item should be highlighted on map if possible

### ISSUE THREAD

**Issue by kdingle** [mshareef123/CCFarmApp#47]
Filter > wine > results > select any on the results > from the selection page > bring up map by going to menu > it would be nice to highlight the location that the user was just looking at (ie. have pop up open on map) if possible.

**Comment by scottwink** [comment]
Add a button to details page "View on map"

**Comment by eaziz** [comment]
Remove link on details page to google maps direction. Add two buttons "View on map"  which brings you to our map and marker info window open for that specific farm. And "Get directions" button that brings to google maps.

**Comment by scottwink** [comment]
Also use the blue buttons instead of white... Bootstrap Class=primary.
If possible, change this everywhere on the site.
